name: stripe_native
description: Create chargeable stripe tokens using Apple and Google Pay. Display native Apple and Google Pay sheets, then collect one-time source tokens.
version: 1.1.3
author: John Blanchard <jnblanchard@mac.com>
homepage: https://www.rbitwo.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.rbitwo.stripe_native
    pluginClass: StripeNativePlugin
